// ========== Status Maps ==========

const normalDepositStatus: Record<number, string> = {
  0: 'NORMAL_DEPOSIT_UNKNOWN',
  1: 'NORMAL_DEPOSIT_PENDING_L1_CREATING',
  2: 'NORMAL_DEPOSIT_PENDING_RISK_CHECKING',
  3: 'NORMAL_DEPOSIT_PENDING_TRADE_PROCESSING',
  4: 'NORMAL_DEPOSIT_SUCCESS_CENSORED',
  5: 'NORMAL_DEPOSIT_SUCCESS_L2_APPROVED',
  10: 'NORMAL_DEPOSIT_FAILED_L1_CANCELD',
  11: 'NORMAL_DEPOSIT_FAILED_L1_FAILURE',
  12: 'NORMAL_DEPOSIT_FAILED_RISK_CHECK_FAILURE',
  13: 'NORMAL_DEPOSIT_FAILED_CENSOR_FAILURE',
  14: 'NORMAL_DEPOSIT_FAILED_L2_REJECTED'
}

const crossDepositStatus: Record<number, string> = {
  0: 'CROSS_DEPOSIT_UNKNOWN',
  1: 'CROSS_DEPOSIT_PENDING_L1_CREATING',
  2: 'CROSS_DEPOSIT_PENDING_RISK_CHECKING',
  3: 'CROSS_DEPOSIT_PENDING_TRADE_NOTIFIED',
  4: 'CROSS_DEPOSIT_L2_TRANSFERED',
  5: 'CROSS_DEPOSIT_PENDING_TRADE_CONFIRMED',
  6: 'CROSS_DEPOSIT_SUCCESS',
  21: 'CROSS_DEPOSIT_FAILED_RISK_CHECK_FAILURE',
  22: 'CROSS_DEPOSIT_FAILED_TRANSFER_OUT'
}

const normalWithdrawStatus: Record<number, string> = {
  0: 'NORMAL_WITHDRAW_UNKNOWN',
  1: 'NORMAL_WITHDRAW_PENDING_RISK_CHECKING',
  2: 'NORMAL_WITHDRAW_PENDING_TRADE_PROCESSING',
  3: 'NORMAL_WITHDRAW_PENDING_L2_APPROVING',
  4: 'NORMAL_WITHDRAW_PENDING_L1_CONFIRMING',
  5: 'NORMAL_WITHDRAW_PENDING_L1_WITHDRAWING',
  6: 'NORMAL_WITHDRAW_SUCCESS_L1_COMPLETED',
  7: 'NORMAL_WITHDRAW_FAILED_RISK_CHECK_FAILURE',
  8: 'NORMAL_WITHDRAW_FAILED_CENSOR_FAILURE',
  9: 'NORMAL_WITHDRAW_FAILED_L2_REJECTED'
}

const fastWithdrawStatus: Record<number, string> = {
  0: 'FAST_WITHDRAW_UNKNOWN',
  1: 'FAST_WITHDRAW_PENDING_RISK_CHECKING',
  2: 'FAST_WITHDRAW_PENDING_L1_TRY',
  3: 'FAST_WITHDRAW_PENDING_CHECKING',
  4: 'FAST_WITHDRAW_PENDING_SUBMIT',
  5: 'FAST_WITHDRAW_PENDING_CHECKING_ACCOUNT',
  6: 'FAST_WITHDRAW_PENDING_CENSORING',
  7: 'FAST_WITHDRAW_PENDING_L1_CONFIRM',
  8: 'FAST_WITHDRAW_PENDING_L1_CONFIRMING',
  9: 'FAST_WITHDRAW_PENDING_CENSORING_CONFIRMING',
  10: 'FAST_WITHDRAW_PENDING_L2_APPROVING',
  11: 'FAST_WITHDRAW_SUCCESS',
  21: 'FAST_WITHDRAW_FAILED_RISK_CHECK_FAILURE',
  22: 'FAST_WITHDRAW_FAILED_L1_TRY_REJECTED',
  23: 'FAST_WITHDRAW_FAILED_TRANSFER_REJECTED',
  24: 'FAST_WITHDRAW_FAILED_CHECKING_ACCOUNT_REJECTED',
  25: 'FAST_WITHDRAW_FAILED_CENSORING',
  26: 'FAST_WITHDRAW_FAILED_L1_CONFIRM_REJECTED',
  27: 'FAST_WITHDRAW_FAILED_L1_REJECTED',
  28: 'FAST_WITHDRAW_FAILED_L2_REJECTED'
}

const crossWithdrawStatus: Record<number, string> = {
  0: 'CROSS_WITHDRAW_UNKNOWN',
  1: 'CROSS_WITHDRAW_PENDING_RISK_CHECKING',
  2: 'CROSS_WITHDRAW_PENDING_CHECKING',
  3: 'CROSS_WITHDRAW_SUCCESS_SUBMIT_CENSOR',
  4: 'CROSS_WITHDRAW_PENDING_CENSOR_CHECKING_ACCOUNT',
  5: 'CROSS_WITHDRAW_PENDING_CENSORING',
  6: 'CROSS_WITHDRAW_PENDING_L2_APPROVING',
  7: 'CROSS_WITHDRAW_PENDING_L1_SUBMIT',
  8: 'CROSS_WITHDRAW_PENDING_L1_CONFIRMING',
  9: 'CROSS_WITHDRAW_SUCCESS',
  21: 'CROSS_WITHDRAW_FAILED_RISK_CHECK_FAILURE',
  22: 'CROSS_WITHDRAW_FAILED_TRANSFER_REJECTED',
  23: 'CROSS_WITHDRAW_FAILED_CENSOR_CHECKING_ACCOUNT_REJECTED',
  24: 'CROSS_WITHDRAW_FAILED_CENSORING',
  25: 'CROSS_WITHDRAW_FAILED_L2_REJECTED',
  26: 'CROSS_WITHDRAW_FAILED_L1_SUBMIT_REJECTED',
  27: 'CROSS_WITHDRAW_FAILED_L1_REJECTED'
}

const transferInOutStatus: Record<number, string> = {
  0: 'UNKNOWN_TRANSFER_STATUS',
  1: 'PENDING_CHECKING',
  2: 'PENDING_CENSORING',
  3: 'SUCCESS_CENSOR_SUCCESS',
  4: 'SUCCESS_L2_APPROVED',
  5: 'FAILED_CHECK_INVALID',
  6: 'FAILED_CENSOR_FAILURE',
  7: 'FAILED_L2_REJECT',
  8: 'FAILED_L2_REJECT_APPROVED'
}


// ========== 常量 ==========

export const ORDER_TYPE = {
  CROSS_DEPOSIT: 'ORDER_TYPE_CROSS_DEPOSIT',
  NORMAL_DEPOSIT: 'ORDER_TYPE_NORMAL_DEPOSIT',
  NORMAL_WITHDRAW: 'ORDER_TYPE_NORMAL_WITHDRAW',
  CROSS_WITHDRAW: 'ORDER_TYPE_CROSS_WITHDRAW',
  FAST_WITHDRAW: 'ORDER_TYPE_FAST_WITHDRAW',
  TRANSFER_OUT: 'ORDER_TYPE_TRANSFER_OUT',
  TRANSFER_IN: 'ORDER_TYPE_TRANSFER_IN'
} as const


// ========== getTransferStatusName ==========

function getTransferStatusName(type: string, status: number): string {
  let name =
    (type === ORDER_TYPE.CROSS_DEPOSIT && crossDepositStatus[status]) ||
    (type === ORDER_TYPE.NORMAL_DEPOSIT && normalDepositStatus[status]) ||
    (type === ORDER_TYPE.CROSS_WITHDRAW && crossWithdrawStatus[status]) ||
    (type === ORDER_TYPE.NORMAL_WITHDRAW && normalWithdrawStatus[status]) ||
    (type === ORDER_TYPE.FAST_WITHDRAW && fastWithdrawStatus[status]) ||
    ((type === ORDER_TYPE.TRANSFER_OUT || type === ORDER_TYPE.TRANSFER_IN) &&
      transferInOutStatus[status]) ||
    ''

  return name || String(status)
}


// ========== ⭐ getStatus 主函数 ==========
export function getPerpStatus(type: string, status: number, getName = true) {
  const $t = getGlobalT()

  const OrderStatus = {
    UnKnown: $t('unKnown1'),
    Pending: $t('confirming'),
    Success: $t('success2'),
    Failed: $t('failed')
  }
  const statusName = getTransferStatusName(type, status)

  if (
    statusName.includes('PENDING') ||
    statusName === 'CROSS_WITHDRAW_SUCCESS_SUBMIT_CENSOR' ||
    statusName === '9999'
  ) {
    return getName ? OrderStatus.Pending :' Pending'
  } else if (
    statusName.includes('SUCCESS') ||
    statusName === 'FAST_WITHDRAW_PENDING_CENSORING_CONFIRMING' ||
    statusName === 'FAST_WITHDRAW_PENDING_L2_APPROVING' ||
    statusName === 'CROSS_DEPOSIT_L2_TRANSFERED'
  ) {
    return getName ? OrderStatus.Success : 'Success'
  } else if (statusName.includes('FAILED')) {
    return getName ? OrderStatus.Failed : 'Failed'
  } else {
    return getName ? OrderStatus.UnKnown : 'UnKnown'
  }
}
